//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCayGiaPha.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CayGiaPhaEntities : DbContext
    {
        public CayGiaPhaEntities()
            : base("name=CayGiaPhaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOAIQUANHE> LOAIQUANHEs { get; set; }
        public virtual DbSet<NGHENGHIEP> NGHENGHIEPs { get; set; }
        public virtual DbSet<QUANHE> QUANHEs { get; set; }
        public virtual DbSet<QUEQUAN> QUEQUANs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
    }
}
