//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCayGiaPha.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIQUANHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAIQUANHE()
        {
            this.QUANHEs = new HashSet<QUANHE>();
        }
    
        public int MaLoaiQuanHe { get; set; }
        public string TenLoaiQuanHe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANHE> QUANHEs { get; set; }
    }
}
