//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCayGiaPha.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANHVIEN()
        {
            this.QUANHEs = new HashSet<QUANHE>();
            this.QUANHEs1 = new HashSet<QUANHE>();
        }
    
        public int MaThanhVien { get; set; }
        public Nullable<int> MaThanhVienCu { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayPhatSinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaQueQuan { get; set; }
        public Nullable<int> MaNgheNghiep { get; set; }
    
        public virtual NGHENGHIEP NGHENGHIEP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANHE> QUANHEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUANHE> QUANHEs1 { get; set; }
        public virtual QUEQUAN QUEQUAN { get; set; }
    }
}
